### ISSUE TITLE
Validating YAML input files

### ISSUE THREAD

**Issue by michal-szostak** [HEPData/hepdata-converter#11]
As there is https://github.com/HEPData/hepdata-validator available, should it be integrated to hepdata-converter for validating input YAML files before conversion? @eamonnmag ?

**Comment by eamonnmag** [comment]
Indeed. That would be very useful :)

**Comment by michal-szostak** [comment]
Alright, I added validation to the hepdata-converter (for input YAML files).

I have a question though - in submission.yaml in the general section which elements are required and which are optional?

**Comment by eamonnmag** [comment]
That is defined in the JSON schema files in the repository. Some
description is also given in the hepdata_submission repo.

**Comment by michal-szostak** [comment]
The issue is resolved, but I'll wait with merging of related branch until it can pass unit tests in Travis, which will be possible after my fixes are merged with hepdata-validator.

**Comment by michal-szostak** [comment]
Now that relevant branch has been long merged to the upstream, I'm closing this issue
