### ISSUE TITLE
Reduce dependencies of hepdata-converter

### ISSUE THREAD

**Issue by dpiparo** [HEPData/hepdata-converter#23]
Hi all,

thanks for providing such a nice tool. It's not obvious to seamlessly convert HEPData yaml files into formats like ROOT Files in a generic way!

I would suggest though to remove the dependencies on ROOTPy and Numpy. Having a small set of depenencies is always of great help when it comes to interoperability and the aforementioned packages are not small.

Here two simple ideas to replace the current usage of the two packages.

### ROOTPy
Rootpy is used only here: https://github.com/HEPData/hepdata-converter/blob/master/hepdata_converter/writers/root_writer.py#L340

One could generate a random long name and delete the file after closing

### Numpy
The only element of Numpy I found in the codebase is numpy.array. This can be replaced directly with the native python array.array class.

**Comment by dpiparo** [comment]
Hi,

I addressed the NumPy part of the issue with this PR: https://github.com/HEPData/hepdata-converter/pull/24

Cheers,
      Danilo

**Comment by dpiparo** [comment]
And also the ROOTPy part was fixed. See https://github.com/HEPData/hepdata-converter/pull/25
Thanks a lot!

**Comment by eamonnmag** [comment]
Thanks Danilo. This is great!
