### ISSUE TITLE
Update hepdata-converter to work with python3

### ISSUE THREAD

**Issue by alisonrclarke** [HEPData/hepdata-converter#30]
Should build on #29

**Comment by alisonrclarke** [comment]
Have contacted the Yoda authors as I'm running into a few issues. Struggling to get Yoda 1.7.7 to compile with python3; Yoda 1.8.0 compiles but there are a couple of issues with the scatter graphs.

**Comment by alisonrclarke** [comment]
Current work is on [DurhamARC/hepdata-converter python3 branch](/DurhamARC/hepdata-converter/tree/feature/python3). Waiting for response from Yoda before continuing.

**Comment by alisonrclarke** [comment]
The latest version of YODA doesn't include the "Variations" lines in the output. Need to determine whether or not this is a problem (the lines are empty in our test file).

**Comment by alisonrclarke** [comment]
The latest 1.8 branch of YODA fixes the above issues, but we need to wait for a new release. See HEPData/hepdata-converter-docker#2

**Comment by alisonrclarke** [comment]
YODA release is out. Now waiting for a new release of HEPData/hepdata-converter-docker on dockerhub.

**Comment by GraemeWatt** [comment]
I've pushed `hepdata/hepdata-converter:0.2.0` to [Docker Hub](https://hub.docker.com/r/hepdata/hepdata-converter).  Can you please open a PR for this issue?

**Comment by alisonrclarke** [comment]
@GraemeWatt I think we're still waiting for this to be pushed to pypi?
