### ISSUE TITLE
RFC OLD HEPData supported fields

### ISSUE THREAD

**Issue by michal-szostak** [HEPData/hepdata-converter#4]
I created new issue so it will (hopefully) be easier to spot.

There are some fields in old HEPData format which do not have one to one mapping to the new format. The ones I know about (found in http://hepdata.cedar.ac.uk/resource/sample.input) are:
* author
* doi
* status
* experiment
* detector
* title

As for now I add those fields at the end of comment section in the new format, but I would like to hear some opinions what should be generally done with "unsupported" input.

Additionaly there are some fields which map to record_ids such as:

* spiresId
* inspireId
* cdsId
* durhamId

I map them to records_ids with ```type``` the same as the field but without "Id" at the end (similar as it's shown in https://github.com/HEPData/hepdata_submission). For example:

```*spiresId: 10412```

is mapped to

```{value: "spires", id: 10412}```

Any comments whether it is expected behavior?

**Comment by eamonnmag** [comment]
Great. The first part is covered mostly from the Inspire input since it also has information about the collaboration e.g. ATLAS, etc. I didn't see these input fields appearing in the actual outputs from the old HEPdata that I saw, but that does not mean they aren't there! @GraemeWatt? For sure, we can drop the author, title, doi, and status. Experiment and detector are also probably unnecessary. But Graeme can confirm.

For the record ids, your approach is exactly correct.

**Comment by GraemeWatt** [comment]
In the new YAML format (e.g. http://hepdata.cedar.ac.uk/view/ins1203852/yaml) we omitted fields from the old input format (e.g. http://hepdata.cedar.ac.uk/view/ins1203852/input) that can be easily obtained from the corresponding Inspire record (e.g. http://inspirehep.net/record/1203852).  Currently, most of these fields can be filled semi-automatically using the "Get started" button at http://hepdata.cedar.ac.uk/input, which simply parses the MARC format of the Inspire record (e.g. http://inspirehep.net/record/1203852/export/hm).  The "status" (i.e. date and responsible person) can be filled automatically from the new submission system and a distinct "durhamId" is probably not necessary in the new system.  All other fields can be obtained from the Inspire record, so I think that all the fields you mention can be dropped in the conversion to the new YAML format.

**Comment by jstypka** [comment]
@GraemeWatt are you parsing somehow the publication date from the MARC from Inspire? Do you have the code for that anywhere?

**Comment by GraemeWatt** [comment]
Mike wrote a Perl script called [getstarted](https://gist.github.com/GraemeWatt/d5e13914127f0a8285de) to parse the MARC format from Inspire (of course, it would be better to use the Inspire API).  Our crude way of guessing the publication year is just to prepend "20" to the first two digits of the arXiv number.  This is not perfect, for example, in this case the arXiv preprint appeared in 2012 and the journal paper was published in 2013, but the user is meant to check and edit the output.

**Comment by jstypka** [comment]
But what about the papers before 2000? Are they assumed to be published in 20XX?

**Comment by GraemeWatt** [comment]
The [getstarted](https://gist.github.com/GraemeWatt/d5e13914127f0a8285de) script only returns a valid publication year for arXiv preprints after 1 April 2007 when the format of the identifier changed from `arXiv:hep-ex/yymmxxx` to `arXiv:yymm.xxxx`.  This is sufficient for the majority of HepData input files currently being prepared by users, and the output of the script is meant to be edited for other cases.  In the new system, a more robust way of extracting the publication date should be found if it is needed, by using the journal reference, for example.
