### ISSUE TITLE
CI with Travis

### ISSUE THREAD

**Issue by eamonnmag** [HEPData/hepdata-converter#6]
See the validator repo for how this is done.

**Comment by michal-szostak** [comment]
to integrate with Travis it seams I have to have administrator rights for the repository - @eamonnmag can something be done about it?

**Comment by eamonnmag** [comment]
Yes. Although I'm away from the computer at the minute. I can give you
access tonight when I get back.

**Comment by michal-szostak** [comment]
Alright, I think it'll also be useful for Coveralls
