### ISSUE TITLE
Submit for install via pip

### ISSUE THREAD

**Issue by eamonnmag** [HEPData/hepdata-converter#8]

**Comment by michal-szostak** [comment]
Alright, I can send it to pytest first, but should I do that with my private pypi account?

**Comment by eamonnmag** [comment]
It's a good point. Perhaps we should have a hepdata account and use that.

**Comment by michal-szostak** [comment]
I agree that it would be better idea.

**Comment by michal-szostak** [comment]
So who shall prepare the account? I don't believe I am an eligible person to do that... (I guess some general hepdata email would be required for this)

**Comment by eamonnmag** [comment]
Just sent you hepdata's login details @michal-szostak

**Comment by michal-szostak** [comment]
Alright, package has been registered and uploaded: https://pypi.python.org/pypi/hepdata-converter/0.1

I think that this issue can be closed now.
