### ISSUE TITLE
hepdata-converter CLI

### ISSUE THREAD

**Issue by michal-szostak** [HEPData/hepdata-converter#9]
For some tests and sanity checks (and to be able to post sample outputs for discussion on GitHub) I implemented rudimentary CLI tools allowing conversions between different formats. Old HEPData has some conversion tools, so I thought that this code can be integrated into the master branch.

Question is - should it remain, or be cleared up? Or some ideas / questions to discuss? @eamonnmag ?

Sample usage:

```
hepdata-converter --input-format yaml --output-format csv --table "Table 1" input output
```
The above line is equivalent to code:

```
#!/usr/bin/python
hepconverter.convert(input, output, options={'input_format': 'yaml',
                                             'output_format': 'csv',
                                             'table': 'Table 1'})
```

All the options required by parsers / writers are automatically accepted from command line so running:

```
hepdata-converter --help
```

will print all information about all supported input and output formats as well as possible parameters for them.

**Comment by eamonnmag** [comment]
If converting all, do you simply remove the table option? Seems nice and simple from this standpoint. @GraemeWatt or @cranmer, any comments?

**Comment by michal-szostak** [comment]
All the options of the CLI are the same as the ones parsed by writer / parser - so as long as CSV writer supports writing all tables (to a different files) it should not be a problem. As for the question whether CSV writer should have functionality of converting all tables in one go it should be discussed in the issue of CSV writer itself.
